src/oauth/urls.py
# flake8: noqa

from rest_auth.urls import urlpatterns as default_urls
from rest_auth.registration.urls import urlpatterns as registration_urls

src/researchhub/urls.py
"""researchhub URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
"""
from django.contrib import admin
from django.urls import include, path, re_path
from rest_framework import routers

import bullet_point.views
import discussion.views
import google_analytics.views
import hub.views
import mailing_list.views
import oauth.urls
import oauth.views
import paper.views
import reputation.views
import researchhub.views
import search.urls
import summary.views
import user.views
import notification.views
import analytics.views
import purchase.views

from researchhub.settings import CLOUD, NO_SILK

router = routers.DefaultRouter()

router.register(
    r'paper/([0-9]+)/discussion/([0-9]+)/comment/([0-9]+)/reply',
    discussion.views.ReplyViewSet,
    basename='discussion_thread_comment_replies'
)

router.register(
    r'paper/([0-9]+)/discussion/([0-9]+)/comment',
    discussion.views.CommentViewSet,
    basename='discussion_thread_comments'
)

router.register(
    r'paper/([0-9]+)/discussion',
    discussion.views.ThreadViewSet,
    basename='discussion_threads'
)

router.register(
    r'paper/discussion/file',
    discussion.views.CommentFileUpload,
    basename='discussion_file_upload'
)


router.register(
    r'paper/([0-9]+)/bullet_point',
    bullet_point.views.BulletPointViewSet,
    basename='bullet_points'
)

router.register(
    r'paper/featured_papers',
    paper.views.FeaturedPaperViewSet,
    basename='featured_papers'
)

router.register(
    r'paper/([0-9]+)/additional_file',
    paper.views.AdditionalFileViewSet,
    basename='additional_files'
)

router.register(
    r'paper',
    paper.views.PaperViewSet,
    basename='paper'
)

router.register(
    r'author',
    user.views.AuthorViewSet,
    basename='author'
)

router.register(
    r'bullet_point',
    bullet_point.views.BulletPointViewSet,
    basename='bullet_point'
)

router.register(
    r'summary',
    summary.views.SummaryViewSet,
    basename='summary'
)

router.register(
    r'hub',
    hub.views.HubViewSet,
    basename='hub'
)

router.register(
    r'hub_category',
    hub.views.HubCategoryViewSet,
    basename='hub_category'
)

router.register(
    r'university',
    user.views.UniversityViewSet,
    basename='university'
)

router.register(
    r'major',
    user.views.MajorViewSet,
    basename='major'
)

router.register(
    r'email_recipient',
    mailing_list.views.EmailRecipientViewSet,
    basename='email_recipient'
)

router.register(
    r'notification',
    notification.views.NotificationViewSet,
    basename='notification'
)

router.register(
    r'figure',
    paper.views.FigureViewSet,
    basename='figure'
)

router.register(
    r'analytics/websiteviews',
    analytics.views.WebsiteVisitsViewSet,
    basename='websiteviews'
)

router.register(
    r'events/paper',
    analytics.views.PaperEventViewSet,
    basename='events_paper'
)

router.register(
    r'events/amplitude/forward_event',
    analytics.views.AmplitudeViewSet,
    basename='events_amplitude'
)

router.register(
    r'purchase',
    purchase.views.PurchaseViewSet,
    basename='purchase'
)

router.register(
    r'support',
    purchase.views.SupportViewSet,
    basename='support'
)

router.register(
    r'stripe',
    purchase.views.StripeViewSet,
    basename='stripe'
)

router.register(r'user', user.views.UserViewSet)

router.register(r'withdrawal', reputation.views.WithdrawalViewSet)

router.register(r'user_verification', user.views.VerificationViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('email_notifications/', mailing_list.views.email_notifications),
    path('health/', researchhub.views.healthcheck),
    path('api/events/forward_event/', google_analytics.views.forward_event),
    re_path(r'^api/', include(router.urls)),
    path(
        'api/permissions/',
        researchhub.views.permissions,
        name='permissions'
    ),
    path('api/search/', include(search.urls)),
    path(
        'api/auth/orcid/login/callback/',
        oauth.views.orcid_callback,
        name='orcid_callback'
    ),
    path(
        'api/auth/orcid/connect/',
        oauth.views.orcid_connect,
        name='orcid_login'
    ),
    path(
        'auth/google/yolo/callback/',
        oauth.views.google_yolo_callback,
        name='google_yolo_callback'
    ),
    path(
        'api/auth/google/yolo/',
        oauth.views.GoogleYoloLogin.as_view(),
        name='google_yolo'
    ),
    path(
        'auth/google/login/callback/',
        oauth.views.google_callback,
        name='google_callback'
    ),
    path(
        'api/auth/captcha_verify/',
        oauth.views.captcha_verify,
        name='captcha_verify'
    ),
    path(
        'api/auth/google/login/',
        oauth.views.GoogleLogin.as_view(),
        name='google_login'
    ),
    path(r'api/auth/', include('rest_auth.urls')),
    re_path(r'^auth/signup/', include(oauth.urls.registration_urls)),
    re_path(r'^auth/', include(oauth.urls.default_urls)),
    path('', researchhub.views.index, name='index'),
]

if not CLOUD and not NO_SILK:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

src/hub/models.py
from django.db import models
from django.db.models import Sum

from slugify import slugify

HELP_TEXT_IS_REMOVED = (
    'Hides the hub because it is not allowed.'
)

def get_default_hub_category():
    """Get or create a default value for the hub categories"""

    return HubCategory.objects.get_or_create(category_name='Other')[0]


class HubCategory(models.Model):
    """A grouping of hubs, organized by category"""

    def __str__(self):
        return self.category_name

    def __int__(self):
        return self.id

    category_name = models.CharField(max_length=1024, unique=True)


class Hub(models.Model):
    """A grouping of papers, organized by subject"""

    UNLOCK_AFTER = 14

    name = models.CharField(max_length=1024, unique=True)
    description = models.TextField(default='')
    hub_image = models.FileField(
        max_length=1024,
        upload_to='uploads/hub_images/%Y/%m/%d',
        default=None,
        null=True,
        blank=True
    )
    slug = models.CharField(max_length=256, unique=True, blank=True, null=True)
    slug_index = models.IntegerField(blank=True, null=True)
    acronym = models.CharField(max_length=255, default='', blank=True)
    is_locked = models.BooleanField(default=False)
    subscribers = models.ManyToManyField(
        'user.User',
        related_name='subscribed_hubs',
        through='HubMembership'
    )
    category = models.ForeignKey(
        HubCategory,
        on_delete=models.CASCADE,
        default=get_default_hub_category
    )
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    subscriber_count = models.IntegerField(default=0)
    paper_count = models.IntegerField(default=0)
    discussion_count = models.IntegerField(default=0)

    is_removed = models.BooleanField(
        default=False,
        help_text=HELP_TEXT_IS_REMOVED
    )

    def __str__(self):
        return '{}, locked: {}'.format(self.name, self.is_locked)

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        self.slugify()
        return super(Hub, self).save(*args, **kwargs)

    def get_subscriber_count(self):
        return self.subscriber_count

    def slugify(self):
        if not self.slug:
            self.slug = slugify(self.name)
            hub_slugs = Hub.objects.filter(
                slug__startswith=self.slug
            ).order_by('slug_index')
            if hub_slugs.exists():
                last_slug = hub_slugs.last()
                if not last_slug.slug_index:
                    self.slug_index = 1
                else:
                    self.slug_index = last_slug.slug_index + 1
                self.slug = self.slug + '-' + str(self.slug_index)
        return self.slug

    def get_discussion_count(self):
        return self.papers.filter(is_removed=False).aggregate(disc=Sum('discussion_count'))['disc'] or 0

    def get_paper_count(self):
        return self.papers.filter(is_removed=False).count()

    def get_subscribers_count(self):
        return self.subscribers.filter(is_suspended=False).count()

    @property
    def paper_count_indexing(self):
        return self.get_paper_count()

    @property
    def subscriber_count_indexing(self):
        return self.get_subscribers_count()

    def unlock(self):
        self.is_locked = False
        self.save(update_fields=['is_locked'])


class HubMembership(models.Model):
    user = models.ForeignKey('user.User', on_delete=models.CASCADE)
    hub = models.ForeignKey(Hub, on_delete=models.CASCADE)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

src/templates/academic_verification_email.html
{% load inlinecss %}
{% load l10n %}
{% load humanize %}
<html>
  <link rel="stylesheet" href="../stylesheets/academic_verification_email.css">  
  <head>
      <meta charset="UTF-8">
      <title></title>
      <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
      <style type="text/css">
        @media only screen and (max-width: 633px) {
          body {
            width: 100%;
            box-sizing: border-box;
          }

          .email {
            box-sizing: border-box;
          }

          .email-body {
            box-sizing: border-box;
          }

          .footer {
            box-sizing: border-box;
          }
          
          .banner-img-container {
            display: none !important;
          }
        }
      </style>
  </head>
  {% inlinecss "academic_verification_email.css" %}
  <body>
    <div class="email">
      <div class="email-body"> 
        <div class="banner-img-container">
          <img class="img-banner" src="https://researchhub-paper-prod.s3-us-west-2.amazonaws.com/email_assets/user_verification.png" />
        </div>
        <div class="email-info">
          <div class="email-header">
            <img class="img-logo" src="https://researchhub-paper-prod.s3-us-west-2.amazonaws.com/email_assets/ResearchHubLogo.png" />
            <div class="header">
              Academic Verification Complete
              <p class="header-message">
                Dear {{ user_name }},
                <br/><br/>
                You've been verified on ResearchHub and we've credited you {{ reward_amount|intcomma }} RSC!
              </p>
              <div class="email-action-container">
                <a class="email-action-button" href="{{ user_profile }}"> 
                  Go To Profile 
                </a>
              </div>
            </div>
          </div>
          <div class="info-img-container">
            <img class="img-info" src="https://researchhub-paper-prod.s3-us-west-2.amazonaws.com/email_assets/background_home+(1).png" />
          </div>
        </div>
      </div>
      <div class="footer">
        <a class="footer-link" href="{{ opt_out }}">Unsubscribe from this list</a>
        <a class="footer-link" href="{{ update_subscription }}">Update subscription preferences</a>
      </div>
    </div>
    <div style="display: none">{% now "U" %}</div>
  </body>
</html>

{% endinlinecss %}

src/templates/admin_panel_input_filter.html
{% load i18n %}
<h3>{% blocktrans with filter_title=title %} By {{ filter_title }} {% endblocktrans %}</h3>
<ul>
  <li>
    {% with choices.0 as all_choice %}
    <form method="GET" action="">
        {% for k, v in all_choice.query_parts %}
        <input type="hidden" name="{{ k }}" value="{{ v }}" />
        {% endfor %}
        <input 
           type="text"
           value="{{ spec.value|default_if_none:'' }}"
          name="{{ spec.parameter_name }}"/>
    </form>
    {% endwith %}
  </li>
</ul>

src/templates/distribution_email.html
{% load inlinecss %}
{% load l10n %}
{% load humanize %}
<html>
  <link rel="stylesheet" href="../stylesheets/distribution_email.css">  
  <head>
      <meta charset="UTF-8">
      <title></title>
      <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
  </head>
  {% inlinecss "distribution_email.css" %}
  <body>
    <div class="email-container">
      <div class="email-header">
        <img class="img-logo" src="https://researchhub-paper-prod.s3-us-west-2.amazonaws.com/email_assets/ResearchHubLogo.png" />
        <div class="header">
          You've earned RSC!
          <p class="header-message">
            Dear {{ user_name }},
            <br/><br/>
            You have earned a total of {{ reward_amount|intcomma }} ResearchCoin{{ reward_amount|pluralize }} this week. Share your earnings along with your referral link below!
            <div class="share-links">
              <a title="Share on Twitter" class="twitter-group social-sharing" href="{{ action_links.twitter }}">
                <div class="share-button-text">
                  Share on Twitter
                </div> 
                <img class="social-button" src="https://researchhub-paper-prod.s3-us-west-2.amazonaws.com/email_assets/Twitter_Social_Icon_Circle_Color.png">
                </img>
              </a>
              <a class="facebook-group social-sharing" href="{{ action_links.facebook }}">
                <div class="share-button-text">
                  Share on Facebook
                </div>
                <img class="social-button" src="https://researchhub-paper-prod.s3-us-west-2.amazonaws.com/email_assets/f_logo_RGB-Blue_250.png"></img>
              </a>
            </div>  
          </p>
        </div>
      </div>
      <div class="content">
        <div class="column-left">
          <h4 class="column-headers"> Papers uploaded </h4>
          <h4 class="column-headers"> Comments made </h4>
          <h4 class="column-headers"> Upvotes given </h4>
        </div>
        <div class="column-center">
          <h4 class="column-values"> {{ uploaded_paper_count }} </h4>
          <h4 class="column-values">{{ discussion_count }}</h4>
          <h4 class="column-values"> {{ total_votes_given }} </h4>
        </div>
        <div class="column-right">
          <h4 class="column-headers"> Upvotes on papers </h4>
          <h4 class="column-headers"> Upvotes on comments </h4>
        </div>
        <div class="column-center">
          <h4 class="column-values"> {{ total_paper_votes }} </h4>
          <h4 class="column-values">{{ total_comment_votes }}</h4>
        </div>
      </div>
      {% if uploaded_papers %}
        <div class="papers-message">
          <h4>Papers You Uploaded</h4>
        </div>
        {% for paper in uploaded_papers %}
          <a href="{{ paper.url }}" class="paper">
            <div class="paper-votes-container">
              <div class="paper-votes-pill"> 
                {{ paper.vote_count }}
              </div>
            </div>
            <div class="paper-info-container">
              <div class="paper-info-body">
                <div class="paper-info-text">
                  <div class="paper-title"> 
                    {{ paper.title }} 
                  </div>
                  <div class="paper-summary">
                    {% if paper.summary %}
                      {{ paper.summary }}
                    {% endif %}
                  </div>
                  <div class="paper-author">
                    Submitted by {{ paper.uploaded_by }}
                  </div>
                </div>
                <div class="paper-preview-container">
                  <img class="paper-preview" src="{{ paper.preview }}"/>
                </div>
              </div>
              <div class="paper-footer">
                <div class="paper-hubs">
                  {% for hub in paper.hubs %}
                    <div class="paper-hub">
                      {{ hub|upper }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </a>
        {% endfor %}
      {% endif %}
    </div>
    <div class="footer">
      <a class="footer-link" href="{{opt_out}}">Unsubscribe from this list</a>
      <a class="footer-link" href="{{update_subscription}}">Update subscription preferences</a>
    </div>
    <div style="display: none">{% now "U" %}</div>
  </body>
</html>

{% endinlinecss %}

src/templates/invite_to_hub_email.html
{% load inlinecss %}

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    </head>
    {% inlinecss "stylesheets/invite_to_hub_email.css" %}
    <body>
        <div class="email-container">
            <div class="email-header">
                <img class="img-logo" src="https://researchhub-paper-prod.s3-us-west-2.amazonaws.com/email_assets/ResearchHubLogo.png" />
                <span class="header-text">
                    You're Invited!
                </span>
            </div>
            <div class="content">
                <div class="tagline">
                    Someone has invited you to join the {{ hub_name }} Hub on Researchhub.
                </div>
                <br/>
                <div>
                    Join now to colaborate with scholars, researchers, and enthusiasts in creating a community invested in expanding research and knowledge in the {{hub_name}} field!
                </div>
                <br/>
                <div class="button-container">
                    <a href={{link}}>
                        <div class="join">
                            <div class="join-text">
                                Join Now
                            </div>
                        </div>
                    </a>
                </div>
                <br/>
            </div>
            <div class="footer">
                If you would like to stop receiving emails from ResearchHub <a href={{opt_out}}>opt-out here</a>
            </div>
        </div>
    </body>
</html>

{% endinlinecss %}

src/templates/monthly_contributors.html
{% extends "admin/base_site.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="{% url 'admin:index' %}">Home</a>
  &rsaquo;
  <a href="/admin/user/">User</a>
  &rsaquo;
  Analytics
</div>
{% endblock %}

{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>

<div style="display: flex; width: 70%;">
  <canvas style="margin-bottom: 30px; width: 55%; height: 45%;" id="contributorsChart"></canvas>
  <div style="display: table-caption; padding: 10px;">
    <div style="padding: 5px">
      <label for="start_date">Start Date:</label>
      <input type="date" id="start_date" name="start_date" value="2020-01-01">
    </div>
    <div style="padding: 5px">
      <label for="end_date">End Date:</label>
      <input type="date" id="end_date" name="end_date" value="2020-01-01">
    </div>
    <div style="display: grid; padding: 5px">
      <label for="days_range">Days Range:</label>
      <select name="days_range" id="days_range">
        <option value="1">30</option>
        <option value="2">60</option>
        <option value="3">90</option>
        <option value="4">120</option>
      </select>
    </div>
    <div style="display: grid; padding: 5px">
      <label for="chart_selector">Chart:</label>
      <select name="chart_selector" id="chart_selector">
        <option value="day">Day</option>
        <option value="month">Month</option>
      </select>
    </div>
    <div style="padding: 5px">
      <button id="reload" style="height: 30px; width: 100%; font-size: 14px">
        Reload Chart Data
      </button>
    </div>
  </div>
  <div style="padding: 10px;">
    <label for="tool_tip_output">Tool Tip Info: Users</label>
    <textarea readonly style="height: 235px; width: 210px; margin-top: 5px;" id='tool_tip_output'></textarea>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const ctx = document.getElementById('contributorsChart').getContext('2d');

    const chartData = {{ chart_data | safe }};

    // Parse the dates to JS
    chartData.forEach((d) => {
      d.x = d.date;
    });

    const contributorsChart = new Chart(ctx, {
      type: 'line',
      data: {
        datasets: [
          {
            label: 'Unique Contributors',
            fill: true,
            data: chartData,
            backgroundColor: 'rgba(220,20,20,0.5)',
          },
        ],
      },
      options: {
        responsive: true,
        tooltips: {
          intersect: true,
          mode: 'x-axis',
            callbacks: {
                label: function(tooltipItem, data) {
                  var userData = data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index].users;
                  var label = "Unique Contributors: " + userData.length;
                  var toolTipTextArea = document.getElementById('tool_tip_output');
                  toolTipTextArea.value = ""

                  userData.forEach((user) => {
                    toolTipTextArea.value += user + "\n"
                  });
                  return label
                }
            }
        },
        scales: {
          xAxes: [
            {
              type: 'time',
              ticks: {
                source: 'data',
              },
              time: {
                unit: 'day',
                displayFormats: {
                  day: 'MMM DD',
                },
              },
            },
          ],
          yAxes: [
            {
              ticks: {
                beginAtZero: true,
              },
            },
          ],
        },
      },
    });

    var date = new Date();
    date = date.toISOString().split('T')[0];
    document.getElementById('end_date').value = date;

    // Reload chart data from the backend on button click
    const reloadButton = document.getElementById('reload');

    reloadButton.addEventListener('click', async() => {
        var data = {
          start_date: document.getElementById('start_date').value,
          end_date: document.getElementById('end_date').value,
          days_range: document.getElementById('days_range').value,
          chart_selector: document.getElementById('chart_selector').value,
        };
        var url = "/admin/user/analyticmodel/chart_data/";
        url += "?start_date=" + data.start_date;
        url += "&end_date=" + data.end_date + "T23:59";
        url += "&days_range=" + data.days_range;
        url += "&chart_selector=" + data.chart_selector;

        const res = await fetch(url);
        const json = await res.json();
        var chartData = json.chart_data;
        chartData.forEach((d) => {
          d.x = d.date
        });

        var xAxisFormat = ''
        if (data.chart_selector === 'day') {
          xAxisFormat = 'MMM DD'
        } else {
          xAxisFormat = 'MMM'
        }
        contributorsChart.data.datasets[0].data = chartData;
        contributorsChart.scales["x-axis-0"].options.time.displayFormats.day = xAxisFormat;
        contributorsChart.update();
      }
    );
  });
</script>
{% endblock %}

src/templates/notification_email.html
{% load inlinecss %}
{% load l10n %}
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    </head>
    {% inlinecss "notification_email.css" %}
    <body>
      <div class="email-container">
        <div class="email-header">
          <img class="img-logo" src="https://researchhub-paper-prod.s3-us-west-2.amazonaws.com/email_assets/ResearchHubLogo.png" />
          <div class="header">
            Your Notifications
          </div>
        </div>
        {% for action in actions %}
          <div class="content">
            <div class="meta">
              <div class="avatar-wrapper">
                {% if action.item.created_by.author_profile.profile_image %}
                  <img
                    class="author-avatar"
                    src="{{ action.item.created_by.author_profile.profile_image|default:"https://lh5.googleusercontent.com/-17a1IzJomPE/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rdlSnx9v1y2976233QPpmGaCpMSXg/photo.jpg" }}"
                    alt="{{ action.item.created_by.author_profile.profile_image }}"
                  />
                {% else %}
                  <div class="initials">
                    {{ action.initials }}
                  </div>
                {% endif %}
              </div>
              <div class="notification-wrapper">
                <div class="notification-title">
                  <span class="first-line">
                    <b>
                      {{ action.item.created_by.author_profile.first_name }}
                       {{ action.item.created_by.author_profile.last_name }}
                    </b> {{ action.label }}:
                  </span>
                  <div class="paper">
                    {{ action.item.paper.title }}
                  </div>
                  <div class="timestamp">
                    <!-- <span class="timestamp-icon">•</span> -->
                    {{ action.created_date|localize }}
                  </div>
                </div>
              </div>
            </div>
            <div class="body">
              {{ action.item.plain_text }}
            </div>
            <div class="hubtags-list">
              <a class="button-label" href="{{ action.frontend_view_link }}">
                View {{ action.content_type_name }}
              </a>
            </div>
            <div class="divider">
              <div class="line"></div>
            </div>
          </div>
        {% endfor %}
      <div class="footer">
        <a href="{{opt_out}}">Unsubscribe or change how frequently I get updated</a>
      </div>
    </body>
</html>

{% endinlinecss %}

src/templates/verification_change_form.html
{% extends 'admin/change_form.html' %}

{% block field_sets %}
	{{ block.super }}
	<fieldset class="module aligned">
		<div class="form-row field-user">
			<label for="id_file">User:</label>
			{{ user|safe }}
			<label for="id_file">Referred By:</label>
			{{ referred_by|safe }}
		</div>
	</fieldset>
	<fieldset class="module aligned" style="padding: 10px;">
		<label for="id_file">Files:</label>
		{{ images|safe }}
	</fieldset>
	<fieldset class="module aligned">
		<div class="form-row field-user">
			<label for="id_user">Academic Verification:</label>
			{{ verified|safe }}
		</div>
	</fieldset>
{% endblock %}

{% block submit_buttons_bottom %}
	<div class="submit-row">
	    <input type="submit" value="Approve" name="_approve">
	    <input type="submit" value="Reject" name="_reject">
	</div>
    {{ block.super }}
{% endblock %}

src/templates/weekly_digest_email.html
{% load inlinecss %}
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title></title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,500&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    </head>
    {% inlinecss "weekly_digest_email.css" %}
    <body>
        <style type="text/css">
            @media only screen and (max-width:767px) {
                .hubs-desktop {display: none!important;}

                .hubs-mobile {display: block!important;}
            }
        </style>
        <div style="display: none; max-height: 0px; overflow: hidden;">
            {{ preview_text }}
        </div>
        <div class="email-container">
            <div class="email-header">
                <div class="flex-text inline">
                    <img class="img-logo" src="https://researchhub-paper-prod.s3-us-west-2.amazonaws.com/email_assets/rh-logo.png" />
                    <div class="first-name">
                        {{ first_name }}'s' Digest
                    </div>
                </div>
            </div>
            <div class="tagline">
                Top Papers For You
            </div>
            {% for paper in papers %}
              <a class="content-container" href="https://www.researchhub.com/paper/{{paper.id}}/summary">
                  <div class="content">
                      <div class="points">
                          <span class="flex-text">
                              {{ paper.calculate_score }}
                          </span>
                      </div>
                      <div class="right">
                        <div class="title">{{paper.title}}</div>
                        <!-- <div class="body">
                            {{paper.tagline}}
                        </div> -->
                        <div class="meta">
                          <div class="author-name">
                              {{paper.author.first_name}} {{paper.author.last_name}}
                          </div>
                          <div class="row">
                              <div class="comments-row">
                                  <img class="comments-logo" src="https://researchhub-paper-prod.s3-us-west-2.amazonaws.com/email_assets/comments.png" /> {{ paper.get_discussion_count }} {% if paper.get_discussion_count == 1 %} comment {% else %} comments {% endif %}
                              </div>
                              <div class="hubs hubs-desktop">
                                  {% for hub in paper.hubs.all %}
                                      <button class="hub">
                                          {{ hub.name }}
                                      </button>
                                {% endfor %}
                              </div>
                          </div>
                      </div>
                      <div class="hubs-mobile">
                          {% for hub in paper.hubs.all %}
                              <button class="hub mobile-hub">
                                  {{ hub.name }}
                              </button>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
              </a>
            {% endfor %}
            <div class="read-more-container">
                <a href="https://www.researchhub.com" class="read-more-button">
                    Read More on ResearchHub
                </a>
            </div>
            <div class="divider">
                <div class="line"></div>
              </div>
        <div class="footer">
            <div>
                This email was sent by ResearchHub
            </div>
            <div>
                If you would like to stop receiving emails from ResearchHub <a href={{opt_out}}>opt-out here</a>
            </div>
        </div>
    </body>
</html>

{% endinlinecss %}